version: "3"
services:
  db:
    image: onenewcode/mysql:chat
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - chat
    healthcheck: # 设置健康检查
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 30s
      retries: 3
  redis:
    image: redis:7.2.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "6379:6379"
    command: ["redis-server"]
    networks:
      - chat
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
  chat:
    image: onenewcode/chat-web:0.1.0
    container_name: chat-web
    networks:
      - chat
    ports:
      - "8082:8082"
    # command: sh -c "/bin/sleep 60"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
networks:
  chat:
    external: false