// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"chat/config"
)

// Injectors from wire.go:

func Initialize() config.Config {
	viper := config.ConfigPath()
	configConfig := config.InitConfig(viper)
	return configConfig
}
