mysql:
  dns: root:root@tcp(121.37.143.160:3306)/ginchat?charset=utf8&parseTime=True&loc=Local
redis:
  addr: "121.37.143.160:6379"
  password: ""
  DB: 0
  poolSize: 30
  minIdleConn: 30
timeout:
  DelayHeartbeat: 3   #延迟心跳时间  单位秒
  HeartbeatHz: 30   #每隔多少秒心跳时间   
  HeartbeatMaxTime: 30000  #最大心跳时间  ，超过此就下线 
  RedisOnlineTime: 4  #缓存的在线用户时长   单位H

port:
  server: ":8080"
  udp: 3001
